name: EZKD
version: 1.2
description: Keep track of your KD
author: Theos
main: com.ezkd.main.EZKD
depend: [Profiler]

commands:
   kd:
      description: Check a targets KD.
      usage: /<command> [player]
permissions:
    ezkd.kd:
        description: Gives access to KD command